# Generated by Django 6.0.3 on 2026-03-16 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoExito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_antes', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen_despues', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Caso de Éxito',
                'verbose_name_plural': 'Casos de Éxito',
                'db_table': 'casos_exito',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada'), ('Reprogramada', 'Reprogramada')], default='Pendiente', max_length=20)),
                ('motivo_cambio', models.TextField(blank=True, null=True)),
                ('servicio_realizado', models.CharField(blank=True, choices=[('Odontología General', 'Odontología General'), ('Limpiezas', 'Limpiezas'), ('Extracciones', 'Extracciones'), ('Caries', 'Caries'), ('Resina', 'Resina'), ('Ortodoncia', 'Ortodoncia'), ('Brackets', 'Brackets'), ('Ortopedia Maxilar', 'Ortopedia Maxilar')], max_length=50, null=True)),
                ('comentario_especialista', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
            },
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'db_table': 'preguntas_frecuentes',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promociones',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='clinica.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='PacientePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('enfermedad_importante', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('tiene_cuenta', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_paciente', to='clinica.usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Paciente',
                'verbose_name_plural': 'Perfiles de Pacientes',
                'db_table': 'pacientes_perfil',
            },
        ),
        migrations.CreateModel(
            name='EspecialistaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp_contacto', models.CharField(blank=True, max_length=30, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_especialista', to='clinica.usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Especialista',
                'verbose_name_plural': 'Perfiles de Especialistas',
                'db_table': 'especialistas_perfil',
            },
        ),
        migrations.CreateModel(
            name='ColaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('SMS', 'SMS'), ('Correo', 'Correo')], max_length=20)),
                ('tipo_aviso', models.CharField(choices=[('24H_CONFIRMACION', '24H_CONFIRMACION'), ('1H_RECORDATORIO', '1H_RECORDATORIO'), ('CUMPLEANOS', 'CUMPLEANOS')], max_length=30)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Fallido', 'Fallido')], default='Pendiente', max_length=20)),
                ('fecha_envio_programada', models.DateTimeField()),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clinica.cita')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clinica.usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'cola_notificaciones',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_especialista', to='clinica.usuario'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to='clinica.usuario'),
        ),
    ]
