# Generated by Django 6.0.3 on 2026-03-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(default=30)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
            },
        ),
        migrations.AddField(
            model_name='especialistaperfil',
            name='anos_experiencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especialistaperfil',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especialistaperfil',
            name='cert_foto_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especialistaperfil',
            name='cert_foto_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especialistaperfil',
            name='cert_foto_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especialistaperfil',
            name='foto_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
